### ISSUE TITLE
Undefined reference error

### ISSUE THREAD

**Issue by tomazvila** [sewenew/redis-plus-plus#218]
I have been trying to include redis to my project. But even with the simplest program I get linker error.
I'm working on Ubuntu 20.04.1 LTS x86_64

I did default installation:
```bash
/usr/local/include
❯ tree
.
├── hiredis
│   ├── adapters
│   │   ├── ae.h
│   │   ├── glib.h
│   │   ├── ivykis.h
│   │   ├── libevent.h
│   │   ├── libev.h
│   │   ├── libuv.h
│   │   ├── macosx.h
│   │   └── qt.h
│   ├── alloc.h
│   ├── async.h
│   ├── hiredis.h
│   ├── read.h
│   └── sds.h
└── sw
    └── redis++
        ├── command_args.h
        ├── command.h
        ├── command_options.h
        ├── connection.h
        ├── connection_pool.h
        ├── errors.h
        ├── pipeline.h
        ├── queued_redis.h
        ├── queued_redis.hpp
        ├── redis_cluster.h
        ├── redis_cluster.hpp
        ├── redis++.h
        ├── redis.h
        ├── redis.hpp
        ├── reply.h
        ├── sentinel.h
        ├── shards.h
        ├── shards_pool.h
        ├── subscriber.h
        ├── tls.h
        ├── transaction.h
        └── utils.h

/usr/local/lib
❯ ls
libhidpp.so  libhiredis.a  libhiredis.so@  libhiredis.so.1.0.1-dev*  libredis++.a  libredis++.so@  libredis++.so.1@  libredis++.so.1.2.3  pkgconfig/  python2.7/  python3.8/
```
My simple code looks like this
```c++
#include <sw/redis++/redis++.h>

int main() {
    auto redis = sw::redis::Redis("tcp://127.0.0.1");
    return 0;
}
```
I have tried 
```bash
user@pc:~/development/project$ g++-4.8 -std=c++11 -I/usr/local/include -L/usr/local/lib  -o test main.cpp  -lredis++ -lhiredis
/usr/bin/ld: /tmp/ccxp8qxJ.o: in function `main':
main.cpp:(.text+0xf0): undefined reference to `sw::redis::Redis::Redis(std::string const&)'
collect2: error: ld returned 1 exit status
user@pc:~/development/project$ g++-4.8 -std=c++11 -o test main.cpp  -lredis++ -lhiredis
/usr/bin/ld: warning: libhiredis.so.1.0.1-dev, needed by /usr/local/lib/libredis++.so, may conflict with libhiredis.so.0.14
/usr/bin/ld: /tmp/ccrFmlXn.o: in function `main':
main.cpp:(.text+0xf0): undefined reference to `sw::redis::Redis::Redis(std::string const&)'
collect2: error: ld returned 1 exit status
user@pc:~/development/project$ g++-4.8 -std=c++11 -I/usr/local/include  -o test main.cpp /usr/local/lib/libhiredis.a /usr/local/lib/libredis++.a
/usr/bin/ld: /tmp/cc2MCJwO.o: in function `main':
main.cpp:(.text+0xf0): undefined reference to `sw::redis::Redis::Redis(std::string const&)'
collect2: error: ld returned 1 exit status
```
At this point I'm starting to think, that this might not be problem from my side, but from the project side.

Any help would be appreciated.

**Comment by sewenew** [comment]
> /usr/bin/ld: warning: libhiredis.so.1.0.1-dev, needed by /usr/local/lib/libredis++.so, may conflict with libhiredis.so.0.14

Error message shows that you might installed more than one version of hiredis. In this case, you might get some wired problems. Please uninstall one of them, and ensure there's only one hiredis version is installed.

Also, in some environment, you might need to link libredis++ before libhiredis. So you can try the following:

```
g++-4.8 -std=c++11 -I/usr/local/include  -o test main.cpp /usr/local/lib/libredis++.a /usr/local/lib/libhiredis.a -pthread
```

Regards

**Comment by tomazvila** [comment]
> > /usr/bin/ld: warning: libhiredis.so.1.0.1-dev, needed by /usr/local/lib/libredis++.so, may conflict with libhiredis.so.0.14
> 
> Error message shows that you might installed more than one version of hiredis. In this case, you might get some wired problems. Please uninstall one of them, and ensure there's only one hiredis version is installed.

Yeah, this was the problem, I had libhiredis.so.0.13 installed.

Thank you for help.
